const mongoose = require("mongoose");
mongoose.Promise = global.Promise;
mongoose
  .connect("mongodb://0.0.0.0:27017/Fyplogin", {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useCreateIndex: true,
  })
  .then(() => {
    console.log("MongoDB connected"); 
  })
  .catch((error) => {
    console.error("MongoDB connection error:", error);
  });

const studentSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
  },
  studentId: {
    type: String,
    required: true,
    //unique: true,
  },
  email: {
    type: String,
    required: true,
    unique: true,
  },
  password: {
    type: String,
    required: true,
  },
  
});
const teacherSchema = new mongoose.Schema({
  teacherId: {
    type: String, // or mongoose.Schema.Types.ObjectId if you want an autogenerated ObjectId
    required: true,
    //unique: true,
  },
  name: {
    type: String,
    required: true,
  },
  project: {
    type: String,
    required: true,
  },
  email: {
    type: String,
    required: true,
    unique: true,
  },
  password: {
    type: String,
    required: true,
  },
});



const coordinatorSchema = new mongoose.Schema({
  email: {
    type: String,
    required: true,
    unique: true,
  },
  password: {
    type: String,
    required: true,
  },
});


const Student = mongoose.model("Students", studentSchema);
const Teacher = mongoose.model("Teachers", teacherSchema);
const Coordinator = mongoose.model("Coordinators", coordinatorSchema);

module.exports = { Student, Teacher, Coordinator };
